[package]
org = "anupama"
name = "testbindgen"
version = "0.1.0"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-text"
version = "1.9"

# transitive dependency of org.apache.commons:commons-text:1.9
[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.11"
